### ISSUE TITLE
How to compile and start on Windows 10?

### ISSUE THREAD

**Issue by vzlomka76** [BenchMine/BenchMine#4]
Hello, can I compile and start BenchMine on Windows 10? I think I can compile with CMake programm for Windows

**Comment by InusualZ** [comment]
Hey, the server it's now production ready. The player only can spawn in an flat world can't do anything, not even move. If you still want to compile it the CMakeLists script should work I think.

**Comment by vzlomka76** [comment]
@InusualZ Yeah, I'll wait for stable build :). I hope the project will not be abandoned
