### ISSUE TITLE
How to initialize Login packet?

### ISSUE THREAD

**Issue by lukeeey** [BenchMine/BenchMine#8]
More of a general C++ question (because i'm dumb).

How would i initialize the Login packet? I can see this code `Login(std::unique_ptr<Packet>&& packet);` but i'm compltely confused. I also cant find where your packet handling is being done.

**Comment by InusualZ** [comment]
All the games packet are handled by an instance of the corresponding [Player](https://github.com/BenchMine/BenchMine/blob/master/source/world/entity/player/Player.cpp). Each player have an [NetworkSession](https://github.com/BenchMine/BenchMine/blob/master/source/world/entity/player/NetworkSession.cpp), which is a class that handle all the networking stuff of the player. The Login packet is used [here](https://github.com/BenchMine/BenchMine/blob/master/source/world/entity/player/NetworkSession.cpp#L93). If you have any other question. Let me know :)

**Comment by lukeeey** [comment]
Is there any reason you have `std::unique_ptr<Packet>` as the paramater of the Login class?

Also, could you possibly help with my server software, or change yours to work with the original C++ RakNet library? Sorry for asking so much but i have no idea how to set up the initial packet handling

**Comment by InusualZ** [comment]
Sorry, I live in Puerto Rico. Right now we are dealing with the aftermath of Hurricane Maria.

**Comment by lukeeey** [comment]
Oh i'm sorry
